### ISSUE TITLE
Questions are not displayed correctly, answers do no work

### ISSUE THREAD

**Issue by Nietzsch3** [zjosua/anki-mc#106]
Hello, 

my new cards do not work, altough I've created them correctly they neither work properly when answering them nor show the right solution. This problem persists with mc, sc and kprim.

![image](https://github.com/zjosua/anki-mc/assets/97446155/38abac21-9c5d-4be3-a3c9-55d877daa014)
![image](https://github.com/zjosua/anki-mc/assets/97446155/9caf4762-f2f9-48c0-9b09-8b4e20c95299)
![image](https://github.com/zjosua/anki-mc/assets/97446155/fed3263a-c999-4ffd-bc6e-73205235e097)

Is there maybe a quick fix for this or are my settings wrong?

Thank you for your help.

**Comment by 3ter** [comment]
I can imagine this could happen due to https://github.com/zjosua/anki-mc/issues/97 when there are (uninented) tables in the answer fields (as the addon currently searches for literal HTML table rows, which probably should be properly identified with an `id` in a future release). Did you by chance create the card from a table?

Did you try creating a new card from scratch (without copy/pasting anything)?

If you want to rule out that your settings are interfering you could run anki in a new (temp) folder, install the addon, create a simple card / import one of your own cards and try it.

**Comment by Nietzsch3** [comment]
I did copy the answers out of a csv-file, could that be the problem?

**Comment by 3ter** [comment]
If you happen to have opened it in Excel or so I fathom this could be it. Or did you have them automatically imported? As in the comment above it would be no trouble to clean those notes up in one go if the culprit is found (and the garbled table view is a good indicator).

I can also offer you to check your note. Export it from anki (use the defaults) and zip it to append it to a message in this issue.

**Comment by 3ter** [comment]
No answer from user
