### ISSUE TITLE
mobile for AnkiDroid

### ISSUE THREAD

**Issue by Bambuspony** [zjosua/anki-mc#4]
here someone perhaps made it mobile available - don't know if it's similiar to this addon or possible https://ankiweb.net/shared/info/413154037 - last comment (or the oldest)

**Comment by zjosua** [comment]
I am planning to do something that works for these cards.
The idea is to add some javascript that test whether the add-on is installed (PC) or not (mobile), and can take care of the formatting and shuffling if the add-on is not installed.
However, I'm afraid I will not find the time to implement this before August.

[Here](https://github.com/zjosua/anki-mc/wiki/MC-without-add-ons) is what I have been using for a while. Unlike the code you linked to, my version allows to shuffle the choices and to colorize the user's choices depending on whether they are correct or not. As a tradeoff, I placed both the question and the answer on the back of the card, because without an add-on, there is no way to make selections made on the front of the card available for evaluation on the back of the card.

**Comment by Bambuspony** [comment]
Works great!
