### ISSUE TITLE
answers don't show

### ISSUE THREAD

**Issue by sammanesh1** [zjosua/anki-mc#49]
answers don't show while reviewing a card on windows. The question shows but there are no multiple choice options. Addon works fine with android.

**Comment by kirbizzle** [comment]
I am having the same issue. I have primarily used this card type for a few years now and since updating I have not been able to see the answer choices. I have re-installed the addon multiple times both manually and via Tools -> Add-ons -> Get Add-ons... with no luck. It seems like some cards work, but if I try to edit them, they no longer display the answer choices for the question.

**Comment by kirbizzle** [comment]
I had to manually edit the card with the code located [here](https://github.com/zjosua/anki-mc/tree/master/card).

Make sure to update all three files. You can do so by going to the addons folder via Tools -> Add-ons -> Multiple Choice for Anki -> View Files or while in editing mode of the card in the Anki application, select "Cards" on the upper left hand corner.

**Comment by 3ter** [comment]
Resolved
