### ISSUE TITLE
import tool

### ISSUE THREAD

**Issue by Bambuspony** [zjosua/anki-mc#5]
another addon would be great, that fills the fields "question" and MC1 to MC5 automatically: so you can copy the question including the answers a to e [trigger for "a", "a)", "(a)", and "A",.. an "1",.. etc.] - paste it and the addon will put it in the right fields - would save a lot of time. Or perhaps even as an multi import tool for a lot of questions and answers - the whole exam in one copy-and-paste procedure to Anki ;-)

**Comment by zjosua** [comment]
Thanks for the suggestion.
In my opinion, importers are not the scope of this add-on, unless there is a standardized way to format multiple choice quizzes, which I honestly doubt.

I do have a python script that converts the practice quizzes from my university's website to csv files that can be imported with Anki's default importer.
If you paste one question in the format you have in mind, I might just take the time to come up with a search and replace regex to convert it to an Anki importable csv.

**Comment by Bambuspony** [comment]
Yes, I understand. You may also give me a hint and I try for myself.
The questions normally look like this:

`
Long question with a lot of, and . and perhaps also a !
Tick only one. Or tick yes or no
a) answer one
b) the right answer`
c) another answer
d) but his could also be A)
e) last answer

Another question with long text ...
1. something true
2. again something true
3. not so true
4. false
5. again true

a) only 1 is true
b) all is true
c) 1, 2, 3 are true
d) 1,2 and 5 are true
e) nothing is true
`

**Comment by zjosua** [comment]
Here's a start:

Search for: `(?s)(.*?)\na\) (.*?)\nb\) (.*?)\nc\) (.*?)\nd\) (.*?)\ne\) (.*?)\n`
Replace with: `"","\1","","\2","\3","\4","\5","\6"\n`

That doesn't do it yet though.
To get a working csv file that can be imported with Anki, the formatting in the questions (especially newlines and lists) need to be recreated with the proper html tags.

For learning and experimenting with regex, I recommend [regex101](https://regex101.com/) (leave a star [here](https://github.com/firasdib/Regex101/) if you like it). 

I'm closing this, because it's too off topic for this repo, but feel free to email me if you need more help.
