### ISSUE TITLE
Fail to load multiple choice in Anki 2.1.40

### ISSUE THREAD

**Issue by starslxd** [zjosua/anki-mc#70]
Thanks for your effort to support this amazing addon!

My multiple choice answer cannot display correctly.  Please find my scrrenshot for your troubleshoot. Thanks!
![Front](https://user-images.githubusercontent.com/8794859/148415582-c676740f-ce48-44bf-bb00-e21a1c2d8846.png)
![Back](https://user-images.githubusercontent.com/8794859/148415578-717c50b1-2ff8-434b-9eb1-bec7395afb09.png)
![Fields](https://user-images.githubusercontent.com/8794859/148415558-ad5cb631-92a6-4d86-9cea-79f8b417fe4d.png)

**Comment by 3ter** [comment]
Hi there, it seems that you
1) are not using the latest version of the addon template (title and question have been switched in a PR a while ago)
![image](https://user-images.githubusercontent.com/11499929/148438253-9f1b8c94-37dd-4c42-88bb-690a2d5fe117.png)
2) mixed up title and question (which cannot be empty)

I hope this helps.

**Comment by starslxd** [comment]
> Hi there, it seems that you
> 
> 1. are not using the latest version of the addon template (title and question have been switched in a PR a while ago)
>    ![image](https://user-images.githubusercontent.com/11499929/148438253-9f1b8c94-37dd-4c42-88bb-690a2d5fe117.png)
> 2. mixed up title and question (which cannot be empty) -> said PR wanted to alleviate this issue
> 
> I hope this helps.

I have deleted and installed the addon last day so that it should be latest version. Where can I download latest version of addon template?

What's mean by your comments?
- point#1: title and question have been switched in a PR a while ago?
- point#2: mixed up title and question (which cannot be empty) -> said PR wanted to alleviate this issue?

**Comment by 3ter** [comment]
> I have deleted and installed the addon last day so that it should be latest version. Where can I download latest version of addon template?

It has been some time since I last updated, so I don't remember if deleting and readding the addon overwrites the local note types (correct me if I'm wrong @zjosua).
If the order is not as in my screenshot above, then it's not the latest version. In this case I'd recommend renaming the note type from the "manage note types" dialogue
![image](https://user-images.githubusercontent.com/11499929/148532414-9438a22d-8fc7-4e98-bbd2-4ab48b767a82.png)
and afterwards reinstall the addon.

In my previous answer I was referring to #36. Did you try moving the title to the question?

**Comment by starslxd** [comment]
It works after renmaing the note type. Then delete and readd the addon.

It doesn't work refer to your answer #36. But another issue happen that I would create another issue log. Thanks!
