### ISSUE TITLE
Is this Add-on reliable?

### ISSUE THREAD

**Issue by shadow9648** [zjosua/anki-mc#80]
Hi, I’m @shadow9648.

I have recently explored your Add-on and I am very happy that I found it. It is a very good feature. I am now putting all my exam questions into it but while doing it, I keep asking myself, if this add-on is reliable?!

Will it definitively show the answers as correct, which I have selected as correct? 

Besides many positive, there are also many negative reviews to this addon.Tthe negative ratings were given before the update.

Did you stabilized your addon with the update of the 2022-04-08, that we students can rely on it 100% and start learning with it?

**Comment by shadow9648** [comment]
And should I add or remove something from the code, or just use it in the actual original type?

**Comment by 3ter** [comment]
I use the template (the addon isn't much more than a note template) without modifications because I like the coloring like it is intended.

**Comment by 3ter** [comment]
The stale PR to which I was referring above has just been merged (#52) - so the maintainer is still active making the project even more reliable so I reckon the issue could be closed.

Thanks @zjosua for your continued efforts 👍

**Comment by zjosua** [comment]
Some users report that the code in the note template doesn't work on their devices. I've never found the cause of that issue, since I cannot reproduce it.
Frankly, I also can't be bothered to make the add-on work for everyone, nor to add all the coloring options people could think of. I have originally just published the code to share it with people who find it useful, without planning to improve or change it much. I am happy to add new options and features, if they are presented as a pull request that does not mess up any existing funtionality. But I don't provide support for isolated cases where the code isn't working and I hardly ever write code for suggested improvements myself.
@3ter thanks a lot for you contributions and interaction with users in PRs and issues.
